// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.oznu;

privileged aspect FormatoOZECNUS0_Roo_Serializable {
    
    //declare parents: FormatoOZECNUS0 implements Serializable;
    
    private static final long FormatoOZECNUS0.serialVersionUID = 1L;
    
}
