// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.oznu;

privileged aspect PeticionTransaccionOznu_Roo_Serializable {
    
    //// PeticionTransaccionOznu implements Serializable;
    
    private static final long PeticionTransaccionOznu.serialVersionUID = 1L;
    
}
