// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.oznu;

privileged aspect RespuestaTransaccionOznu_Roo_Serializable {
    
    //// RespuestaTransaccionOznu implements Serializable;
    
    private static final long RespuestaTransaccionOznu.serialVersionUID = 1L;
    
}
