// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.customers.dao.model.oznb;

import java.lang.String;

privileged aspect FormatoOZNCENB0_Roo_JavaBean {
    
    public String FormatoOZNCENB0.getClveacc() {
        return this.clveacc;
    }
    
    public void FormatoOZNCENB0.setClveacc(String clveacc) {
        this.clveacc = clveacc;
    }
    
}
