// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.customers.dao.model.oznb;

privileged aspect PeticionTransaccionOznb_Roo_Serializable {
    
    //// PeticionTransaccionOznb implements Serializable;
    
    private static final long PeticionTransaccionOznb.serialVersionUID = 1L;
    
}
