// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.customers.dao.model.oznp;

import java.io.Serializable;

privileged aspect FormatoOZECNPS0_Roo_Serializable {
    
    declare parents: FormatoOZECNPS0 implements Serializable;
    
    private static final long FormatoOZECNPS0.serialVersionUID = 1L;
    
}
