// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.customers.dao.model.oznp;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOznp_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOznp implements Serializable;
    
    private static final long RespuestaTransaccionOznp.serialVersionUID = 1L;
    
}
