// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.customers.dao.model.oznw;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOznw_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOznw implements Serializable;
    
    private static final long RespuestaTransaccionOznw.serialVersionUID = 1L;
    
}
