// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.loan.dao.model.oznj;

import java.lang.String;

privileged aspect FormatoOZNCENJ0_Roo_JavaBean {
    
    public String FormatoOZNCENJ0.getNumprod() {
        return this.numprod;
    }
    
    public void FormatoOZNCENJ0.setNumprod(String numprod) {
        this.numprod = numprod;
    }
    
}
