// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.loan.dao.model.oznj;

import java.lang.String;

privileged aspect FormatoOZNCENJ0_Roo_ToString {
    
    public String FormatoOZNCENJ0.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Nomtarj: ").append(getNomtarj());
        return sb.toString();
    }
    
}
