// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.accounts.dao.model.oznu;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOznu_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOznu implements Serializable;
    
    private static final long RespuestaTransaccionOznu.serialVersionUID = 1L;
    
}
