// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.globalposition.dao.model.ozn0;

privileged aspect PeticionTransaccionOzn0_Roo_Serializable {
    
    // PeticionTransaccionOzn0 implements Serializable;
    
    private static final long PeticionTransaccionOzn0.serialVersionUID = 1L;
    
}
