// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.ozny;

privileged aspect RespuestaTransaccionOzny_Roo_Serializable {
    
    //// RespuestaTransaccionOzny implements Serializable;
    
    private static final long RespuestaTransaccionOzny.serialVersionUID = 1L;
    
}
