// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.executives.dao.model.oznr;

import java.lang.String;

privileged aspect FormatoOZECNRE0_Roo_ToString {
    
    public String FormatoOZECNRE0.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Idusuar: ").append(getIdusuar());
        return sb.toString();
    }
    
}
