// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.executives.dao.model.oznr;

import java.io.Serializable;

privileged aspect FormatoOZECNRE0_Roo_Serializable {
    
    declare parents: FormatoOZECNRE0 implements Serializable;
    
    private static final long FormatoOZECNRE0.serialVersionUID = 1L;
    
}
