package com.bbva.czic.checkbooks.business.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bbva.jee.arq.spring.core.log.I18nLog;
import com.bbva.jee.arq.spring.core.log.I18nLogFactory;

import com.bbva.jee.arq.spring.core.servicing.utils.BusinessServicesToolKit;

import com.bbva.czic.checkbooks.business.dto.DTOIntEnumCheckStatus;
import com.bbva.czic.checkbooks.business.dto.DTOIntCheck;
import com.bbva.czic.checkbooks.business.dto.DTOIntCheckbook;
import com.bbva.czic.checkbooks.business.dto.DTOIntEnumCheckbookStatus;
import com.bbva.czic.checkbooks.business.ISrvIntCheckbooks;


@Service
public class SrvIntCheckbooks implements ISrvIntCheckbooks {
	
	private static I18nLog log = I18nLogFactory.getLogI18n(SrvIntCheckbooks.class,"META-INF/spring/i18n/log/mensajesLog");

	@Autowired
	BusinessServicesToolKit bussinesToolKit;
	
	
	@Override
	public List<DTOIntCheck> getChecks(String idCheckbook) {
		//TODO: autogenerated, complete implementation using DAO
		return null;
	}

		
	@Override
	public List<DTOIntCheckbook> getCheckbooks() {
		//TODO: autogenerated, complete implementation using DAO
		return null;
	}

	

}
