// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.customers.dao.model.oznb;

import java.io.Serializable;

privileged aspect FormatoOZNCENB0_Roo_Serializable {
    
    declare parents: FormatoOZNCENB0 implements Serializable;
    
    private static final long FormatoOZNCENB0.serialVersionUID = 1L;
    
}
