// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.customers.dao.model.oznb;

import java.io.Serializable;

privileged aspect PeticionTransaccionOznb_Roo_Serializable {
    
    declare parents: PeticionTransaccionOznb implements Serializable;
    
    private static final long PeticionTransaccionOznb.serialVersionUID = 1L;
    
}
