package com.bbva.czic.internationalcontracttransfer.business.impl;

import java.util.List;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bbva.czic.internationalcontracttransfer.business.ISrvIntInternationalContractTransfer;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntFilterInternationalContractTransfers;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntInternationalContractTransfer;
import com.bbva.jee.arq.spring.core.servicing.utils.BusinessServicesToolKit;

@Service
public class SrvIntInternationalContractTransfer implements ISrvIntInternationalContractTransfer {

	private static Log log = LogFactory.getLog(SrvIntInternationalContractTransfer.class);

	@Autowired
	BusinessServicesToolKit bussinesToolKit;

	@Override
	public List<DTOIntInternationalContractTransfer> listInternationalContractTransfer(
			DTOIntFilterInternationalContractTransfers filterInternationalContractTransfer) {
		// TODO: autogenerated, complete implementation using DAO
		return null;
	}

}
