package com.bbva.czic.internationalcontracttransfer.business.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import org.apache.commons.logging.Log;
import org.apache.commons.logging.LogFactory;

import com.bbva.jee.arq.spring.core.servicing.utils.BusinessServicesToolKit;

import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntProduct;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntIdentityDocument;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntPerson;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntDocument;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntAddress;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntContract;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntExchangeRate;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntExternalReference;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntInternationalContractTransfer;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntBank;
import com.bbva.czic.internationalcontracttransfer.business.dto.DTOIntCountry;
import com.bbva.czic.internationalcontracttransfer.business.ISrvIntInternationalContractTransfer;


@Service
public class SrvIntInternationalContractTransfer implements ISrvIntInternationalContractTransfer {
	
	private static Log log = LogFactory.getLog(SrvIntInternationalContractTransfer.class);

	@Autowired
	BusinessServicesToolKit bussinesToolKit;
	
	
	@Override
	public List<DTOIntInternationalContractTransfer> listInternationalContractTransfer() {
		//TODO: autogenerated, complete implementation using DAO
		return null;
	}

	

}
