// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.globalposition.dao.model.ozn1;
import java.io.Serializable;
privileged aspect FormatoOZECN1E0_Roo_Serializable {
    
    declare parents: FormatoOZECN1E0 implements Serializable;
    
    private static final long FormatoOZECN1E0.serialVersionUID = 1L;
    
}
