// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.globalposition.dao.model.ozn1;

privileged aspect PeticionTransaccionOzn1_Roo_Serializable {
    
    // PeticionTransaccionOzn1 implements Serializable;
    
    private static final long PeticionTransaccionOzn1.serialVersionUID = 1L;
    
}
