// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.globalposition.dao.model.oznh;

privileged aspect PeticionTransaccionOznh_Roo_Serializable {
    
    // PeticionTransaccionOznh implements Serializable;
    
    private static final long PeticionTransaccionOznh.serialVersionUID = 1L;
    
}
