// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.loan.dao.model.oznj;

import java.lang.String;

privileged aspect FormatoOZNCENJ0_Roo_JavaBean {
    
    public String FormatoOZNCENJ0.getNomtarj() {
        return this.nomtarj;
    }
    
    public void FormatoOZNCENJ0.setNomtarj(String nomtarj) {
        this.nomtarj = nomtarj;
    }
    
}
