// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.loan.dao.model.oznj;

privileged aspect PeticionTransaccionOznj_Roo_Serializable {
    
    // PeticionTransaccionOznj implements Serializable;
    
    private static final long PeticionTransaccionOznj.serialVersionUID = 1L;
    
}
