// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.loan.dao.model.ozni;

privileged aspect RespuestaTransaccionOzni_Roo_Serializable {
    
    // RespuestaTransaccionOzni implements Serializable;
    
    private static final long RespuestaTransaccionOzni.serialVersionUID = 1L;
    
}
