// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.globalposition.dao.model.ozn1;

import java.io.Serializable;

privileged aspect FormatoOZECN1S1_Roo_Serializable {
    
    declare parents: FormatoOZECN1S1 implements Serializable;
    
    private static final long FormatoOZECN1S1.serialVersionUID = 1L;
    
}
