// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.globalposition.dao.model.ozn1;

import java.lang.String;

privileged aspect FormatoOZECN1E0_Roo_ToString {
    
    public String FormatoOZECN1E0.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Numclie: ").append(getNumclie());
        return sb.toString();
    }
    
}
