// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.movements.dao.model.oznl;

import java.io.Serializable;

privileged aspect FormatoOZECNLE0_Roo_Serializable {
    
    declare parents: FormatoOZECNLE0 implements Serializable;
    
    private static final long FormatoOZECNLE0.serialVersionUID = 1L;
    
}
