// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.loan.dao.model.oznj;

import java.io.Serializable;

privileged aspect PeticionTransaccionOznj_Roo_Serializable {
    
    declare parents: PeticionTransaccionOznj implements Serializable;
    
    private static final long PeticionTransaccionOznj.serialVersionUID = 1L;
    
}
