// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.accounts.dao.model.ozna;

import java.lang.String;

privileged aspect FormatoOZNCENA0_Roo_JavaBean {
    
    public String FormatoOZNCENA0.getNumprod() {
        return this.numprod;
    }
    
    public void FormatoOZNCENA0.setNumprod(String numprod) {
        this.numprod = numprod;
    }
    
}
