// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.accounts.dao.model.ozna;

import java.io.Serializable;

privileged aspect PeticionTransaccionOzna_Roo_Serializable {
    
    declare parents: PeticionTransaccionOzna implements Serializable;
    
    private static final long PeticionTransaccionOzna.serialVersionUID = 1L;
    
}
