// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.oznt;

import java.lang.String;

privileged aspect FormatoOZECNTE0_Roo_JavaBean {
    
    public String FormatoOZECNTE0.getNumprod() {
        return this.numprod;
    }
    
    public void FormatoOZECNTE0.setNumprod(String numprod) {
        this.numprod = numprod;
    }
    
}
