// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.oznt;
import java.io.Serializable;
privileged aspect FormatoOZECNTS0_Roo_Serializable {
    
    declare parents: FormatoOZECNTS0 implements Serializable;
    
    private static final long FormatoOZECNTS0.serialVersionUID = 1L;
    
}
