// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.oznt;

import java.lang.String;

privileged aspect FormatoOZECNTS1_Roo_ToString {
    
    public String FormatoOZECNTS1.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Titular: ").append(getTitular());
        return sb.toString();
    }
    
}
