// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.oznt;

privileged aspect RespuestaTransaccionOznt_Roo_Serializable {
    
    // RespuestaTransaccionOznt implements Serializable;
    
    private static final long RespuestaTransaccionOznt.serialVersionUID = 1L;
    
}
