// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.accounts.dao.model.oznv;

import java.io.Serializable;

privileged aspect FormatoOZECNVE0_Roo_Serializable {
    
    declare parents: FormatoOZECNVE0 implements Serializable;
    
    private static final long FormatoOZECNVE0.serialVersionUID = 1L;
    
}
