// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.ozn2;

import java.io.Serializable;
privileged aspect FormatoOZECN2S0_Roo_Serializable {
    
    declare parents: FormatoOZECN2S0 implements Serializable;
    
    private static final long FormatoOZECN2S0.serialVersionUID = 1L;
    
}
