// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.ozn2;

import com.bbva.jee.arq.spring.core.host.CuerpoMultiparte;

privileged aspect PeticionTransaccionOzn2_Roo_JavaBean {
    
    public void PeticionTransaccionOzn2.setCuerpo(CuerpoMultiparte cuerpo) {
        this.cuerpo = cuerpo;
    }
    
}
