// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.ozn2;

privileged aspect RespuestaTransaccionOzn2_Roo_Serializable {
    
    // RespuestaTransaccionOzn2 implements Serializable;
    
    private static final long RespuestaTransaccionOzn2.serialVersionUID = 1L;
    
}
