// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.oznm;

privileged aspect RespuestaTransaccionOznm_Roo_Serializable {
    
    // RespuestaTransaccionOznm implements Serializable;
    
    private static final long RespuestaTransaccionOznm.serialVersionUID = 1L;
    
}
