package com.bbva.czic.customers.business.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bbva.jee.arq.spring.core.log.I18nLog;
import com.bbva.jee.arq.spring.core.log.I18nLogFactory;

import com.bbva.jee.arq.spring.core.servicing.utils.BusinessServicesToolKit;

import com.bbva.czic.customers.business.dto.DTOIntCreditCard;
import com.bbva.czic.customers.business.dto.DTOIntProduct;
import com.bbva.czic.customers.business.dto.DTOIntCardCharge;
import com.bbva.czic.customers.business.dto.DTOIntAccMovementsResume;
import com.bbva.czic.customers.business.dto.DTOIntUser;
import com.bbva.czic.customers.business.dto.DTOIntEnumCardChargeCategory;
import com.bbva.czic.customers.business.dto.DTOIntEnumMonth;
import com.bbva.czic.customers.business.ISrvIntCustomers;


@Service
public class SrvIntCustomers implements ISrvIntCustomers {
	
	private static I18nLog log = I18nLogFactory.getLogI18n(SrvIntCustomers.class,"META-INF/spring/i18n/log/mensajesLog");

	@Autowired
	BusinessServicesToolKit bussinesToolKit;
	
	
	@Override
	public List<DTOIntCreditCard> getlistCreditCardsCharges(String idUser) {
		//TODO: autogenerated, complete implementation using DAO
		return null;
	}

		
	@Override
	public List<DTOIntAccMovementsResume> getlistAccountsMovementsResume(String idUser) {
		//TODO: autogenerated, complete implementation using DAO
		return null;
	}

	

}
