// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.customers.dao.model.oznp;

privileged aspect PeticionTransaccionOznp_Roo_Serializable {
    
    //// PeticionTransaccionOznp implements Serializable;
    
    private static final long PeticionTransaccionOznp.serialVersionUID = 1L;
    
}
