// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.globalposition.dao.model.oznh;

import java.io.Serializable;

privileged aspect PeticionTransaccionOznh_Roo_Serializable {
    
    declare parents: PeticionTransaccionOznh implements Serializable;
    
    private static final long PeticionTransaccionOznh.serialVersionUID = 1L;
    
}
