// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.globalposition.dao.model.oznh;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOznh_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOznh implements Serializable;
    
    private static final long RespuestaTransaccionOznh.serialVersionUID = 1L;
    
}
