// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.products.dao.model.oznl;

import java.io.Serializable;

privileged aspect PeticionTransaccionOznl_Roo_Serializable {
    
    declare parents: PeticionTransaccionOznl implements Serializable;
    
    private static final long PeticionTransaccionOznl.serialVersionUID = 1L;
    
}
