// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.customers.dao.model.oznq;

privileged aspect PeticionTransaccionOznq_Roo_Serializable {
    
    // PeticionTransaccionOznq implements Serializable;
    
    private static final long PeticionTransaccionOznq.serialVersionUID = 1L;
    
}
