// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.products.dao.model.oznt;

import java.io.Serializable;

privileged aspect FormatoOZECNTE0_Roo_Serializable {
    
    declare parents: FormatoOZECNTE0 implements Serializable;
    
    private static final long FormatoOZECNTE0.serialVersionUID = 1L;
    
}
