// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.products.dao.model.oznt;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOznt_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOznt implements Serializable;
    
    private static final long RespuestaTransaccionOznt.serialVersionUID = 1L;
    
}
