// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.oznv;

privileged aspect FormatoOZECNVS0_Roo_Serializable {
    
    //declare parents: FormatoOZECNVS0 implements Serializable;
    
    private static final long FormatoOZECNVS0.serialVersionUID = 1L;
    
}
