// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.oznv;

privileged aspect PeticionTransaccionOznv_Roo_Serializable {
    
    //// PeticionTransaccionOznv implements Serializable;
    
    private static final long PeticionTransaccionOznv.serialVersionUID = 1L;
    
}
