// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.oznv;

privileged aspect RespuestaTransaccionOznv_Roo_Serializable {
    
    //// RespuestaTransaccionOznv implements Serializable;
    
    private static final long RespuestaTransaccionOznv.serialVersionUID = 1L;
    
}
