// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.cards.dao.model.ozno;

import java.io.Serializable;

privileged aspect PeticionTransaccionOzno_Roo_Serializable {
    
    declare parents: PeticionTransaccionOzno implements Serializable;
    
    private static final long PeticionTransaccionOzno.serialVersionUID = 1L;
    
}
