// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.customers.dao.model.oznw;

privileged aspect RespuestaTransaccionOznw_Roo_Serializable {
    
    // RespuestaTransaccionOznw implements Serializable;
    
    private static final long RespuestaTransaccionOznw.serialVersionUID = 1L;
    
}
