// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.loan.dao.model.ozni;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOzni_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOzni implements Serializable;
    
    private static final long RespuestaTransaccionOzni.serialVersionUID = 1L;
    
}
