// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.customers.dao.model.oznz;

import java.io.Serializable;

privileged aspect PeticionTransaccionOznz_Roo_Serializable {
    
    declare parents: PeticionTransaccionOznz implements Serializable;
    
    private static final long PeticionTransaccionOznz.serialVersionUID = 1L;
    
}
