// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.accounts.dao.model.oznx;

import java.io.Serializable;

privileged aspect FormatoOZECNXE0_Roo_Serializable {
    
    declare parents: FormatoOZECNXE0 implements Serializable;
    
    private static final long FormatoOZECNXE0.serialVersionUID = 1L;
    
}
