// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.accounts.dao.model.oznx;

import java.io.Serializable;

privileged aspect PeticionTransaccionOznx_Roo_Serializable {
    
    declare parents: PeticionTransaccionOznx implements Serializable;
    
    private static final long PeticionTransaccionOznx.serialVersionUID = 1L;
    
}
