// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.products.dao.model.ozn2;

import java.io.Serializable;

privileged aspect PeticionTransaccionOzn2_Roo_Serializable {
    
    declare parents: PeticionTransaccionOzn2 implements Serializable;
    
    private static final long PeticionTransaccionOzn2.serialVersionUID = 1L;
    
}
