// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.loan.dao.model.oznk;

privileged aspect PeticionTransaccionOznk_Roo_Serializable {
    
    // PeticionTransaccionOznk implements Serializable;
    
    private static final long PeticionTransaccionOznk.serialVersionUID = 1L;
    
}
