// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.oznl;

privileged aspect PeticionTransaccionOznl_Roo_Serializable {
    
    // PeticionTransaccionOznl implements Serializable;
    
    private static final long PeticionTransaccionOznl.serialVersionUID = 1L;
    
}
