// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.products.dao.model.oznl;

privileged aspect RespuestaTransaccionOznl_Roo_Serializable {
    
    // RespuestaTransaccionOznl implements Serializable;
    
    private static final long RespuestaTransaccionOznl.serialVersionUID = 1L;
    
}
