// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.loan.dao.model.oznk;

import java.lang.String;

privileged aspect FormatoOZNCENK0_Roo_JavaBean {
    
    public String FormatoOZNCENK0.getNomoper() {
        return this.nomoper;
    }
    
    public void FormatoOZNCENK0.setNomoper(String nomoper) {
        this.nomoper = nomoper;
    }
    
}
