// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.customers.dao.model.oznq;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOznq_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOznq implements Serializable;
    
    private static final long RespuestaTransaccionOznq.serialVersionUID = 1L;
    
}
