// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.executives.dao.model.oznr;

import java.lang.String;

privileged aspect FormatoOZECNRE0_Roo_JavaBean {
    
    public String FormatoOZECNRE0.getIdusuar() {
        return this.idusuar;
    }
    
    public void FormatoOZECNRE0.setIdusuar(String idusuar) {
        this.idusuar = idusuar;
    }
    
}
