// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.executives.dao.model.oznr;

import com.bbva.jee.arq.spring.core.host.CuerpoMultiparte;

privileged aspect PeticionTransaccionOznr_Roo_JavaBean {
    
    public void PeticionTransaccionOznr.setCuerpo(CuerpoMultiparte cuerpo) {
        this.cuerpo = cuerpo;
    }
    
}
