// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.executives.dao.model.oznr;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOznr_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOznr implements Serializable;
    
    private static final long RespuestaTransaccionOznr.serialVersionUID = 1L;
    
}
