// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.cards.dao.model.ozno;

privileged aspect FormatoOZECNOE0_Roo_Serializable {
    
   // declare parents: FormatoOZECNOE0 implements Serializable;
    
    private static final long FormatoOZECNOE0.serialVersionUID = 1L;
    
}
