// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.checkbooks.dao.model.ozns;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOzns_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOzns implements Serializable;
    
    private static final long RespuestaTransaccionOzns.serialVersionUID = 1L;
    
}
