// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.ozna;

privileged aspect FormatoOZNCSNA0_Roo_Serializable {
    
    //declare parents: FormatoOZNCSNA0 implements Serializable;
    
    private static final long FormatoOZNCSNA0.serialVersionUID = 1L;
    
}
