// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.ozna;

import java.lang.String;

privileged aspect FormatoOZNCENA0_Roo_ToString {
    
    public String FormatoOZNCENA0.toString() {
        StringBuilder sb = new StringBuilder();
        sb.append("Numprod: ").append(getNumprod());
        return sb.toString();
    }
    
}
