package com.bbva.czic.loan.business.impl;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bbva.czic.dto.net.Loan;
import com.bbva.czic.loan.business.ISrvIntLoan;
import com.bbva.czic.loan.business.dto.DTOIntLoan;
import com.bbva.czic.loan.business.dto.DTOIntRotaryQuotaMovement;
import com.bbva.czic.loan.dao.LoanDAO;
import com.bbva.jee.arq.spring.core.log.I18nLog;
import com.bbva.jee.arq.spring.core.log.I18nLogFactory;
import com.bbva.jee.arq.spring.core.servicing.gce.BusinessServiceException;
import com.bbva.jee.arq.spring.core.servicing.utils.BusinessServicesToolKit;

@Service
public class SrvIntLoan implements ISrvIntLoan {

	private static I18nLog log = I18nLogFactory.getLogI18n(SrvIntLoan.class, "META-INF/spring/i18n/log/mensajesLog");

	@Autowired
	BusinessServicesToolKit bussinesToolKit;

	private LoanDAO loanDao;

	@Override
	public Loan getRotaryQuota(String idRotaryQuota) throws BusinessServiceException {
		Loan loan = new Loan();

		DTOIntLoan dtoIntLoan = loanDao.getRotaryQuota(idRotaryQuota);
		loan.setPayment(dtoIntLoan.getPayment());
		loan.setStatus(dtoIntLoan.getStatus());
		loan.setBalance(dtoIntLoan.getBalance());

		return loan;
	}

	@Override
	public List<Loan> listRotaryQuotaMovements(Date starDate, Date endDate, String paginationKey, Integer pageSize,
			String idLoan) throws BusinessServiceException {
		Loan loan = null;
		List<Loan> loanList = new ArrayList<Loan>();
		List<DTOIntLoan> intLoan = loanDao.listRotaryQuotaMovements(starDate, endDate, paginationKey, pageSize, idLoan);
		for (DTOIntLoan item : intLoan) {
			loan = new Loan();
			loanList.add(loan);
		}
		return loanList;
	}

	@Override
	public DTOIntRotaryQuotaMovement getRotaryQuotaMovement(String idRotaryQuotaMovement) {
		// TODO: autogenerated, complete implementation using DAO
		return null;
	}

}
