// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.checkbooks.dao.model.ozns;

import java.io.Serializable;

privileged aspect FormatoOZECNSE0_Roo_Serializable {
    
    declare parents: FormatoOZECNSE0 implements Serializable;
    
    private static final long FormatoOZECNSE0.serialVersionUID = 1L;
    
}
