// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.products.dao.model.oznm;

import java.io.Serializable;

privileged aspect PeticionTransaccionOznm_Roo_Serializable {
    
    declare parents: PeticionTransaccionOznm implements Serializable;
    
    private static final long PeticionTransaccionOznm.serialVersionUID = 1L;
    
}
