// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.checkbooks.dao.model.ozny;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOzny_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOzny implements Serializable;
    
    private static final long RespuestaTransaccionOzny.serialVersionUID = 1L;
    
}
