// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.globalposition.dao.model.ozn0;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOzn0_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOzn0 implements Serializable;
    
    private static final long RespuestaTransaccionOzn0.serialVersionUID = 1L;
    
}
