package com.bbva.czic.accounts.business.impl;

import java.util.Date;
import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bbva.czic.accounts.business.ISrvIntAccounts;
import com.bbva.czic.accounts.business.dto.DTOIntAccount;
import com.bbva.czic.accounts.business.dto.DTOIntMovement;
import com.bbva.czic.accounts.dao.AccountsDAO;
import com.bbva.czic.accounts.dao.AccountsDAOImpl;
import com.bbva.jee.arq.spring.core.log.I18nLog;
import com.bbva.jee.arq.spring.core.log.I18nLogFactory;
import com.bbva.jee.arq.spring.core.servicing.utils.BusinessServicesToolKit;

@Service
public abstract class SrvIntAccounts implements ISrvIntAccounts {

	private static I18nLog log = I18nLogFactory
			.getLogI18n(SrvIntAccounts.class, "META-INF/spring/i18n/log/mensajesLog");

	@Autowired
	BusinessServicesToolKit bussinesToolKit;
	
	private AccountsDAOImpl accountsDAOImpl;

	@Override
	public DTOIntMovement getMovement(String idAccount, String idMovement) {
		accountsDAOImpl.toString();
		return null;
	}

	@Override
	public List<DTOIntAccount> listMovements() {
		// TODO: autogenerated, complete implementation using DAO
		return null;
	}

	@Override
	public List<DTOIntAccount> getAccountMonthlyBalance() {
		// TODO: autogenerated, complete implementation using DAO
		return null;
	}

	@Override
	public List<DTOIntAccount> getAccMovementResume() {
		// TODO: autogenerated, complete implementation using DAO
		return null;
	}

	@Override
	public AccountsDAO getAccount(String idAccount) {
		// TODO: autogenerated, complete implementation using DAO
		return null;
	}

	@Override
	public List<DTOIntAccount> getAccountMonthlyBalance(String id,
			Date startMonth, Date endMonth) {
		// TODO Auto-generated method stub
		return null;
	}

	@Override
	public List<DTOIntAccount> getAccMovementResume(String income,
			String outcome, String balance, String month) {
		// TODO Auto-generated method stub
		return null;
	}

}
