package com.bbva.czic.movements.business.impl;

import java.util.List;

import com.bbva.czic.movements.business.dto.*;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bbva.jee.arq.spring.core.log.I18nLog;
import com.bbva.jee.arq.spring.core.log.I18nLogFactory;

import com.bbva.jee.arq.spring.core.servicing.utils.BusinessServicesToolKit;

import com.bbva.czic.movements.business.ISrvIntMovements;


@Service
public class SrvIntMovements implements ISrvIntMovements {
	
	private static I18nLog log = I18nLogFactory.getLogI18n(SrvIntMovements.class,"META-INF/spring/i18n/log/mensajesLog");

	@Autowired
	BusinessServicesToolKit bussinesToolKit;
	
	
	@Override
	public DTOIntMovement getMovement(DTOIntMovementsFilter dtoIntMovementsFilter) {
		//TODO: autogenerated, complete implementation using DAO
		return null;
	}

		
	@Override
	public DTOIntMovement listMovements(String idMovement) {
		//TODO: autogenerated, complete implementation using DAO
		return null;
	}

	

}
