// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.ozns;

privileged aspect PeticionTransaccionOzns_Roo_Serializable {
    
    //// PeticionTransaccionOzns implements Serializable;
    
    private static final long PeticionTransaccionOzns.serialVersionUID = 1L;
    
}
