// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.accounts.dao.model.ozns;

privileged aspect RespuestaTransaccionOzns_Roo_Serializable {
    
    //// RespuestaTransaccionOzns implements Serializable;
    
    private static final long RespuestaTransaccionOzns.serialVersionUID = 1L;
    
}
