// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.customers.dao.model.oznz;
import java.io.Serializable;
privileged aspect FormatoOZECNZE0_Roo_Serializable {
    
    declare parents: FormatoOZECNZE0 implements Serializable;
    
    private static final long FormatoOZECNZE0.serialVersionUID = 1L;
    
}
