// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.customers.dao.model.oznz;

privileged aspect PeticionTransaccionOznz_Roo_Serializable {
    
    // PeticionTransaccionOznz implements Serializable;
    
    private static final long PeticionTransaccionOznz.serialVersionUID = 1L;
    
}
