// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.zic.customers.dao.model.oznz;

privileged aspect RespuestaTransaccionOznz_Roo_Serializable {
    
    // RespuestaTransaccionOznz implements Serializable;
    
    private static final long RespuestaTransaccionOznz.serialVersionUID = 1L;
    
}
