package com.bbva.czic.globalposition.business.impl;

import java.util.List;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.stereotype.Service;

import com.bbva.jee.arq.spring.core.log.I18nLog;
import com.bbva.jee.arq.spring.core.log.I18nLogFactory;

import com.bbva.jee.arq.spring.core.servicing.utils.BusinessServicesToolKit;

import com.bbva.czic.globalposition.business.dto.DTOIntEnumProductType;
import com.bbva.czic.globalposition.business.dto.DTOIntEnumFinancialStatusType;
import com.bbva.czic.globalposition.business.dto.DTOIntProduct;
import com.bbva.czic.globalposition.business.dto.DTOIntOperation;
import com.bbva.czic.globalposition.business.dto.DTOIntEnumContactSourceType;
import com.bbva.czic.globalposition.business.dto.DTOIntPhoneNumber;
import com.bbva.czic.globalposition.business.dto.DTOIntContactInformation;
import com.bbva.czic.globalposition.business.dto.DTOIntEmail;
import com.bbva.czic.globalposition.business.dto.DTOIntMovement;
import com.bbva.czic.globalposition.business.dto.DTOIntEnumPhoneNumberType;
import com.bbva.czic.globalposition.business.ISrvIntGlobalPosition;


@Service
public class SrvIntGlobalPosition implements ISrvIntGlobalPosition {
	
	private static I18nLog log = I18nLogFactory.getLogI18n(SrvIntGlobalPosition.class,"META-INF/spring/i18n/log/mensajesLog");

	@Autowired
	BusinessServicesToolKit bussinesToolKit;
	
	
	@Override
	public List<DTOIntProduct> getExtractGlobalBalance() {
		//TODO: autogenerated, complete implementation using DAO
		return null;
	}

		
	@Override
	public void update(String idProduct, DTOIntProduct infoProduct) {
		//TODO: autogenerated, complete implementation using DAO
	}

	

}
