// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.movements.dao.model.oznm;

import java.io.Serializable;

privileged aspect FormatoOZNCSNM0_Roo_Serializable {
    
    declare parents: FormatoOZNCSNM0 implements Serializable;
    
    private static final long FormatoOZNCSNM0.serialVersionUID = 1L;
    
}
