// WARNING: DO NOT EDIT THIS FILE. THIS FILE IS MANAGED BY SPRING ROO.
// You may push code into the target .java compilation unit if you wish to edit any member(s).

package com.bbva.czic.movements.dao.model.oznm;

import java.io.Serializable;

privileged aspect RespuestaTransaccionOznm_Roo_Serializable {
    
    declare parents: RespuestaTransaccionOznm implements Serializable;
    
    private static final long RespuestaTransaccionOznm.serialVersionUID = 1L;
    
}
